feat: adding controller.
egp1020/LabBackend pull request #14
Opened 2024-10-30 22:37 UTC by egp1020

2024-10-30 23:31 UTC, Xiomara18b commented on src/main/java/culturemedia/controller/CultureMediaController.java
> +import culturoteca.exception.VideoNotFoundException;
is : import culturemedia.exception.VideoNotFoundException;

2024-10-30 23:32 UTC, Xiomara18b commented on src/main/java/culturemedia/controller/CultureMediaController.java
> +import culturoteca.model.Video;
is : import culturemedia.model.Video;

2024-10-30 23:33 UTC, Xiomara18b commented on src/main/java/culturemedia/controller/CultureMediaController.java
> +import culturoteca.service.impl.CultureMediaServiceImpl;
is : import culturemedia.service.impl.CultureMediaServiceImpl;

2024-10-31 00:13 UTC, Xiomara18b requested changes
Please review and change

2024-10-31 00:13 UTC, Xiomara18b commented on src/main/java/culturemedia/controller/CultureMediaController.java
> +package culturoteca.controllers;
the package name is controller, no controllers and culturemedia, not culturoteca

2024-10-31 00:13 UTC, Xiomara18b commented on src/main/java/culturemedia/controller/CultureMediaController.java
> +        List<Video> videos = null;
initialization videos = null; unnecesary

2024-10-31 00:13 UTC, Xiomara18b commented on src/main/java/culturemedia/controller/CultureMediaController.java
> +        videos = cultureMediaService.findAll();
the correct form is: List<Video> videos = cultureMediaService.findAll();

2024-10-31 00:13 UTC, Xiomara18b commented on src/main/java/culturemedia/controller/CultureMediaController.java
> +    public List<Video> find_allVideos() throws VideoNotFoundException {
the name should be : findAllVideos()

2024-10-31 00:13 UTC, Xiomara18b commented on src/main/java/culturemedia/controller/CultureMediaController.java
> +import culturoteca.service.impl.CultureMediaServiceImpl;
is : import culturemedia.service.impl.CultureMediaService;
the CultureMediaService interface is imported, not the implementation

2024-10-31 00:13 UTC, Xiomara18b commented on src/main/java/culturemedia/controller/CultureMediaController.java
> +    private final CultureMediaServiceImpl cultureMediaService;
the interface is used, not the impl

2024-10-31 00:13 UTC, Xiomara18b commented on src/main/java/culturemedia/controller/CultureMediaController.java
> +import culturoteca.model.Video;
is : import culturemedia.model.Video;

2024-10-31 00:13 UTC, Xiomara18b commented on src/main/java/culturemedia/controller/CultureMediaController.java
> +import culturoteca.exception.VideoNotFoundException;
is : import culturemedia.exception.VideoNotFoundException;

2024-10-31 00:13 UTC, Xiomara18b commented on src/main/java/culturemedia/controller/CultureMediaController.java
> +
missing method to add videos

2024-10-31 00:38 UTC, egp1020 commented
Cambios realizados, muchas gracias por tu aporte.

2024-10-31 00:39 UTC, merged